// 内置插件的中文展示文案。只改变视图，不改模块身份、模型工具说明或第三方包元数据。
export const builtinDescriptions: Readonly<Record<string, string>> = Object.freeze({
  persona: '定义 SaCode 的身份、角色和工作风格，作为系统提示词的一部分。',
  'agent-instructions': '读取工作区中的 AGENTS.md、CLAUDE.md 等指令文件，为当前会话提供项目约定。',
  'tool-bash': '让模型执行 Bash 命令，并接入后台任务管理和沙箱权限审批。',
  'tool-pwsh': '让模型执行 PowerShell 命令，共用终端执行、取消和权限控制。',
  'tool-fs': '提供文件读取、写入和编辑工具，接入文件访问与修改权限控制。',
  'tool-fs-search': '使用 ripgrep 按文件名或内容搜索工作区。',
  'tool-jobs': '查看后台任务列表、读取任务输出，并停止指定任务。',
  'skill-filesystem': '从本地文件系统发现技能，提供技能说明和相关资源。',
  'tool-skill': '让模型按需加载技能说明，辅助完成当前任务。',
  'command-goal': '通过斜杠指令创建和管理当前会话中的持久目标。',
  'tool-goal': '让模型读取和更新会话目标，执行时检查对应授权。',
  'tool-ask-user': '让模型向用户提出问题，并等待用户的选择或回答。',
  'tool-todo': '让模型创建和更新任务清单，记录计划及执行进度。',
  'tool-web-search': '让模型使用已配置的搜索服务查找网络信息。',
  'tool-web-fetch': '让模型读取指定网页的内容。',
  'tool-subagent': '派发子智能体任务，并收集其进展和执行结果。',
  'agent-loop': '组织模型请求与工具执行循环，处理取消、重试和轮次结算。',
  'system-prompt': '按已启用的插件和会话配置组装模型实际使用的系统提示词。',
  approval: '管理工具执行审批及其授权范围，记录允许或拒绝的结果。',
  'permission-presets': '按权限预设控制工具访问和审批方式。',
  'browser-use': '接入浏览器操作提供方，将浏览器工具纳入统一执行流程。',
  'computer-use': '接入电脑操作驱动，提供应用观察与操作工具。',
  'office-to-pdf': '将 Office 文档转换为 PDF，供只读预览使用。',
  compaction: '压缩会话上下文，保留后续执行所需的信息。',
  goal: '保存会话目标及其状态，管理目标的执行生命周期。',
  plan: '保存并展示任务计划及步骤状态。',
  'token-meter': '记录模型用量，提供上下文占用和预算相关读数。',
  'ui-agent-preset': '查看和配置 Agent 预设及其会话插件组合。',
  'ui-approval': '展示工具审批请求，并提交用户的审批决定。',
  'ui-attachment': '上传和展示会话附件，提供图片预览。',
  'ui-chat': '展示会话消息、流式答复及关联的工具结果。',
  'ui-commands': '提供会话斜杠指令的发现和选择入口。',
  'ui-conversation': '承载会话视图、输入框及聊天和轨迹等视图切换。',
  'ui-deliverables': '展示任务生成的文件及其他交付物。',
  'ui-directory-picker-browse': '通过目录浏览界面选择工作区目录。',
  'ui-directory-picker-native': '通过系统原生目录选择器选择工作区目录。',
  'ui-goal': '展示和控制会话目标，提供编辑、暂停和恢复入口。',
  'ui-jobs': '展示后台任务状态、输出及停止入口。',
  'ui-layout': '组织导航、会话区域和侧栏的页面布局。',
  'ui-message-feedback': '收集用户对会话消息的反馈。',
  'ui-model-selection': '选择当前会话使用的提供商和模型。',
  'ui-open-in-app': '提供在对应本地应用中打开内容的入口。',
  'ui-permission-presets': '选择和查看会话权限预设。',
  'ui-plan': '展示任务计划及各步骤的执行状态。',
  'ui-plugin-manager': '查看、安装和管理插件及其组成的组件。',
  'ui-reference': '展示会话引用及其关联内容。',
  'ui-schedule': '展示和管理自动化任务及其执行状态。',
  'ui-session': '展示会话状态及相关操作入口。',
  'ui-settings': '承载设置页面及插件贡献的设置分区。',
  'ui-settings-agent-loop': '配置模型与工具循环的执行选项。',
  'ui-settings-general': '承载通用设置窗口和功能插件贡献的偏好配置。',
  'ui-settings-models': '管理模型提供商、模型清单及凭据配置入口。',
  'ui-settings-plugin-inventory': '按全局和会话预设展示内置插件清单及运行状态。',
  'ui-settings-plugins': '承载内置插件列表和插件配置页面。',
  'ui-settings-session-log': '查看和下载会话日志。',
  'ui-settings-shell': '配置终端命令的超时和输出限制。',
  'ui-settings-subagent': '配置子智能体的层级、数量和模型。',
  'ui-settings-web-search': '配置网络搜索服务及请求限制。',
  'ui-shortcuts': '展示和编辑快捷键配置。',
  'ui-sidebar-browser': '在侧栏展示浏览器内容及操作状态。',
  'ui-sidebar-documentpreview': '在侧栏预览 PDF 和 Office 等文档。',
  'ui-sidebar-files': '展示工作区文件树及文件操作入口。',
  'ui-sidebar-right': '承载会话右侧栏的插件视图。',
  'ui-sidebar-terminal': '在侧栏展示终端输出和执行状态。',
  'ui-sidebar': '承载侧栏布局和插件入口。',
  'ui-skill': '展示可用技能及其加载入口。',
  'ui-slots': '按插件贡献组装界面槽位，处理注册、替换和卸载。',
  'ui-subagent': '展示子智能体任务的进展和结果。',
  'ui-theme': '提供界面主题及外观样式。',
  'ui-tool': '展示工具调用、参数、结果和执行状态。',
  'ui-trajectory': '按轮次查看执行轨迹、模型请求、工具调用及真实时序。',
  'ui-user-questions': '展示模型提出的问题，收集用户的选择或回答。',
  'ui-workflow-run': '展示工作流的步骤、进度及执行结果。',
  'ui-workspace': '展示工作区、会话目录及相关管理入口。',
});

export function builtinDescription(moduleName: string, original?: string, zhCN?: string): string | undefined {
  if (zhCN?.trim()) return zhCN;
  // 只识别内置身份及明确的官方命名空间，不根据第三方包的末段名称猜身份。
  const id = moduleName.startsWith('@deepseek-ai/dsh-')
    ? moduleName.slice('@deepseek-ai/dsh-'.length).replace(/^client-/, '')
    : moduleName.startsWith('@sacode/') ? moduleName.slice('@sacode/'.length).replace(/^(?:client-|host-)/, '')
    : moduleName.startsWith('sacode-') ? moduleName.slice('sacode-'.length).replace(/^(?:client-|host-)/, '') : moduleName;
  return Object.prototype.hasOwnProperty.call(builtinDescriptions, id) ? builtinDescriptions[id] : original;
}
