//! Shell 补全脚本生成 — `sacode completions <bash|zsh|powershell|fish>`。
//!
//! D13 提议默认的轻量实现：不迁移 clap（避免重写自研 arg_parser 与 32 个解析测试），
//! 而是从 `SUBCOMMAND_NAMES` 单一清单生成各 shell 补全脚本，覆盖子命令名与常用标志。
//! 子命令清单与 `arg_parser::simple_subcommand` 同源维护（见下方 `sync_guard` 测试）。

use anyhow::Result;

/// 顶层子命令清单（单一真源）。
///
/// 与 `arg_parser::simple_subcommand` 的匹配表保持同步——`subcommand_list_is_current`
/// 测试在两处漂移时失败，强制维护者同步。
pub(super) const SUBCOMMAND_NAMES: &[&str] = &[
    "profile",
    "plugin",
    "doctor",
    "diff",
    "hooks",
    "ide",
    "config",
    "keybindings",
    "outstyle",
    "prompt",
    "wiki",
    "vim",
    "skill",
    "sandbox",
    "mcp",
    "memory",
    "insight",
    "acp",
    "account",
    "audit",
    "design",
    "git",
    "lsp",
    "serve",
    "init",
    "mistakes",
    "checkpoint",
    "status",
    "update",
    "session",
    "dump-config",
    "bundle",
    "task",
    "queue",
    "automation",
    "agent-backends",
    "knowledge",
    "completions",
];

/// 非枚举入口子命令（parse_args 中单独处理，不进 simple_subcommand 匹配表）。
const EXTRA_COMMANDS: &[&str] = &["init-deep", "repl", "tui", "orchestrator"];

/// 顶层运行标志（sacode "<task>" 路径）。
const RUN_FLAGS: &[&str] = &[
    "--mode",
    "--max-iterations",
    "--json",
    "--json-stream",
    "--prompt",
    "--approve",
    "--deny",
    "--profile",
    "--agent-loop",
    "--remote",
    "--help",
    "--version",
];

fn all_commands() -> Vec<&'static str> {
    let mut all = SUBCOMMAND_NAMES.to_vec();
    all.extend_from_slice(EXTRA_COMMANDS);
    all
}

pub fn run(sub_args: Vec<String>) -> Result<()> {
    let shell = sub_args
        .first()
        .map(|s| s.trim().to_ascii_lowercase())
        .unwrap_or_default();
    let script = match shell.as_str() {
        "bash" => bash_script(),
        "zsh" => zsh_script(),
        "powershell" | "pwsh" => powershell_script(),
        "fish" => fish_script(),
        "help" | "--help" | "-h" | "" => {
            println!("{}", help_text());
            return Ok(());
        }
        other => anyhow::bail!("未知 shell：{other}（支持 bash / zsh / powershell / fish）"),
    };
    print!("{script}");
    Ok(())
}

fn help_text() -> String {
    [
        "sacode completions — 生成 shell 补全脚本",
        "",
        "用法：",
        "  sacode completions bash        # Bash 补全",
        "  sacode completions zsh         # Zsh 补全",
        "  sacode completions powershell  # PowerShell 参数补全",
        "  sacode completions fish        # Fish 补全",
        "",
        "安装示例：",
        "  sacode completions bash > ~/.local/share/bash-completion/completions/sacode",
        "  sacode completions zsh > ~/.zfunc/_sacode   # fpath 含 ~/.zfunc 且 compinit 已启用",
        "  sacode completions fish > ~/.config/fish/completions/sacode.fish",
        "  PowerShell: sacode completions powershell > $PROFILE 所指文件中追加",
    ]
    .join("\n")
}

fn bash_script() -> String {
    let commands = all_commands().join(" ");
    let flags = RUN_FLAGS.join(" ");
    format!(
        r#"# sacode bash completion — generated by `sacode completions bash`
_sacode() {{
    local cur prev
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    prev="${{COMP_WORDS[COMP_CWORD-1]}}"
    local commands="{commands}"
    local flags="{flags}"
    if [[ $COMP_CWORD -eq 1 ]]; then
        # 首参数：子命令；以 - 开头时给运行标志；否则双通道（子命令 + 任务词）
        if [[ "$cur" == -* ]]; then
            COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        else
            COMPREPLY=( $(compgen -W "$commands $flags" -- "$cur") )
        fi
        return 0
    fi
    case "$prev" in
        --mode) COMPREPLY=( $(compgen -W "plan build auto yolo" -- "$cur") ) ;;
        --profile) COMPREPLY=( $(compgen -W "$(sacode profile ls 2>/dev/null | tail -n +2 | awk '{{print $1}}')" -- "$cur") ) ;;
        *) COMPREPLY=( $(compgen -f -- "$cur") ) ;;
    esac
    return 0
}}
complete -F _sacode sacode
"#
    )
}

fn zsh_script() -> String {
    let commands = all_commands().join(" ");
    let flags = RUN_FLAGS.join(" ");
    format!(
        r#"#compdef sacode
# sacode zsh completion — generated by `sacode completions zsh`
_sacode() {{
    local -a commands flags
    commands=({commands})
    flags=({flags})
    if (( CURRENT == 2 )); then
        _describe 'subcommand' commands
        _describe 'flag' flags
        return
    fi
    case $words[2] in
        --mode) _values 'mode' plan build auto yolo ;;
        *) _files ;;
    esac
}}
_sacode "$@"
"#
    )
}

fn powershell_script() -> String {
    let commands = all_commands()
        .iter()
        .map(|c| format!("'{c}'"))
        .collect::<Vec<_>>()
        .join(", ");
    let flags = RUN_FLAGS
        .iter()
        .map(|f| format!("'{f}'"))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        r#"# sacode PowerShell completion — generated by `sacode completions powershell`
# 加入 $PROFILE：sacode completions powershell >> $PROFILE
Register-ArgumentCompleter -Native -CommandName sacode -ScriptBlock {{
    param($wordToComplete, $commandAst, $cursorPosition)
    $commands = @({commands})
    $flags = @({flags})
    if ($commandAst.CommandElements.Count -le 2) {{
        $candidates = $commands + $flags
    }} else {{
        $candidates = @()
    }}
    $candidates | Where-Object {{ $_ -like "$wordToComplete*" }} | ForEach-Object {{
        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
    }}
}}
"#
    )
}

fn fish_script() -> String {
    let commands = all_commands()
        .iter()
        .map(|c| format!("complete -c sacode -n '__fish_use_subcommand' -a '{c}' -d 'sacode {c}'"))
        .collect::<Vec<_>>()
        .join("\n");
    let flags = RUN_FLAGS
        .iter()
        .map(|f| format!("complete -c sacode -n '__fish_use_subcommand' -l '{}' -d '{f}'", f.trim_start_matches('-')))
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        r#"# sacode fish completion — generated by `sacode completions fish`
{commands}
{flags}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    /// 同步守卫：SUBCOMMAND_NAMES 与 arg_parser::simple_subcommand 的匹配表必须一致。
    /// 漂移时此测试失败，提示维护者同步两处。
    #[test]
    fn subcommand_list_is_current() {
        // arg_parser 是 cmd 模块私有函数，这里通过 parse_args 间接校验：
        // 清单中每个名字都必须被解析为对应子命令（不落入 Run 路径）。
        for name in SUBCOMMAND_NAMES {
            let options = super::super::parse_args(vec![name.to_string()]);
            // 所有清单成员都是简单子命令，解析后 prompt 为空且非 Run
            assert!(
                !matches!(
                    options.command,
                    super::super::CliCommand::Run | super::super::CliCommand::Help
                ),
                "子命令 {name} 未被 arg_parser 识别——SUBCOMMAND_NAMES 与 arg_parser 漂移"
            );
        }
        // init-deep / repl / tui / orchestrator 单独处理，也验证非 Run/Help
        for name in EXTRA_COMMANDS {
            let options = super::super::parse_args(vec![name.to_string()]);
            assert!(
                !matches!(options.command, super::super::CliCommand::Run),
                "额外子命令 {name} 未被识别"
            );
        }
    }

    #[test]
    fn bash_script_lists_all_commands() {
        let script = bash_script();
        assert!(script.contains("complete -F _sacode sacode"));
        assert!(script.contains("agent-backends"));
        assert!(script.contains("--mode"));
        assert!(script.contains("init-deep"));
    }

    #[test]
    fn powershell_script_registers_completer() {
        let script = powershell_script();
        assert!(script.contains("Register-ArgumentCompleter -Native -CommandName sacode"));
        assert!(script.contains("'knowledge'"));
    }

    #[test]
    fn fish_script_generates_complete_lines() {
        let script = fish_script();
        assert!(script.contains("complete -c sacode"));
        assert!(script.contains("task"));
    }
}
