pub(super) const HELP_LINES: &[&str] = &[
    "SaCode",
    "",
    "Usage:",
    "  sacode \"<task>\" [--mode plan|build|auto] [--max-iterations N] [--json] [--prompt|--approve|--deny]",
    "  sacode orchestrator \"<task>\"",
    "  sacode profile [ls|use <name>|show]",
    "  sacode plugin [list]",
    "  sacode doctor",
    "  sacode diff [--cached]",
    "  sacode hooks",
    "  sacode ide [status|vscode|cursor|jetbrains|install|config show|path|set acp|lsp --host HOST --port PORT]",
    "  sacode config [show|path|user ...|project ...|set <key> <value>|clear <key>]",
    "  sacode keybindings",
    "  sacode outstyle [show|concise|explain|teach|clear|path|project ...]",
    "  sacode prompt [show [task...]|doctor|edit project]",
    "  sacode wiki",
    "  sacode vim [show|on|off|project show|on|off]",
    "  sacode skill [search|install|list|show|update|remove|run]",
    "  sacode sandbox [show [plan|build|auto] [--json]|diff [plan|build|yolo] [--json]|doctor [plan|build|yolo] [--json]|init|path|set <mode> <key> <value>|clear <mode> <key>]",
    "  sacode mcp [search|install|list|show|enable|disable|remove|inspect|tools|call]",
    "  sacode memory [show|list|search <query>|path|summary|append <content> [--type memory|preference|workflow|decision] [--global|-g]|promote <entry_id>|approve <entry_id>|reject <entry_id>|archive <entry_id>|migrate]",
    "  sacode insight",
    "  sacode acp [serve|status] [--host HOST] [--port PORT]",
    "  sacode account [login|status|logout|models]  # saai 统一身份（sa-idp OIDC）",
    "  sacode design [list|show|variants|apply]    # AIDesign TD 示例 + AI 设计变体",
    "  sacode audit [path] | diff [--staged|--base REF] | pr [NUMBER] [--publish] | fix --from report.json  # 全量/差分/PR 审计",
    "  sacode git auth [login github|gitee|status|logout|credential|set-token]  # Git 平台 OAuth/token",
    "  sacode lsp [serve|status] [--tcp] [--host HOST] [--port PORT]",
    "  sacode serve [--acp] [--lsp] [--host HOST] [--port PORT|--port0] [--ready-file PATH] [--auth-token TOKEN] [--open-access]",
    "  sacode init       # 轻量初始化，识别技术栈和基础项目信息",
    "  sacode init-deep  # 深度初始化，生成严格协作配置和工作流",
    "  sacode mistakes [list|show <index>|learn <index>]",
    "  sacode status",
    "  sacode task [list|show|result|cancel|delete <id>]          # 任务管理（daemon 瘦客户端）",
    "  sacode queue [status|pending]                              # 队列状态",
    "  sacode automation [list|create|run|delete|history]         # 定时自动化规则",
    "  sacode agent-backends [list|set|probe]                     # Agent 后端管理",
    "  sacode knowledge [list|search <关键词>] [--scope user|project]  # 知识库检索",
    "  sacode completions [bash|zsh|powershell|fish]              # 生成 shell 补全脚本",
    "  sacode update [--check|--force|--rollback]",
    "  sacode repl",
    "  sacode tui",
    "  sacode --help",
    "  sacode --version",
];

pub(super) fn print_help() {
    for line in HELP_LINES {
        println!("{}", line);
    }
}
