import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,mkdtempSync,writeFileSync,mkdirSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {stripTypeScriptTypes,createRequire} from 'node:module';
import {resolve,join} from 'node:path';
import {fixtureHostEnv} from '../test-support/fixture-env.mjs';
const source=readFileSync(new URL('../renderer/pages/execution-task-state.ts',import.meta.url),'utf8');
const {createExecutionTask}=await import('data:text/javascript;base64,'+Buffer.from(stripTypeScriptTypes(source)).toString('base64'));
const proposal=JSON.stringify({cwd:'D:/workspace',workspaceRevision:1,executable:'cmd',argv:['/c','echo x'],timeoutMs:1000,outputLimit:64});
const snapshot=(phase='awaiting-approval',revision=1)=>({sessionId:'current',executionId:'execution-2',taskId:'t',requestId:'r',proposal,proposalDigest:'a'.repeat(64),revision,phase,result:'',providerAvailable:false,approvalArguments:'exact bytes 中文'});
const deferred=()=>{let resolve;return{promise:new Promise(r=>resolve=r),resolve:v=>resolve(v)};};
function fixture(extra={}){const calls=[];const api={workspaceGet:async()=>({sessionId:'current',directory:'D:/workspace',revision:1,available:true,configured:true}),executionPropose:async(...a)=>{calls.push(['propose',...a]);return snapshot();},executionDescribe:async(...a)=>{calls.push(['describe',...a]);return snapshot();},executionStart:async(...a)=>{calls.push(['start',...a]);return snapshot('running',3);},executionStop:async(...a)=>{calls.push(['stop',...a]);return snapshot('cancelled-before-start',2);},approvalAsk:async(...a)=>{calls.push(['ask',...a]);return{approvalId:9};},approvalAnswer:async(...a)=>{calls.push(['answer',...a]);return{accepted:true};},executionAuthorize:async(...a)=>{calls.push(['authorize',...a]);return snapshot('admitted',2);},...extra};let session='current';const view=createExecutionTask(api,()=>session,()=>{});return{view,calls,change:v=>session=v};}
test('工作区与提案迟到响应不能落到切换后的会话',async()=>{for(const method of ['workspaceGet','executionPropose']){const wait=deferred();const f=fixture({[method]:()=>wait.promise});const pending=method==='workspaceGet'?f.view.workspace():f.view.propose('t','r',proposal);f.change('other');f.view.reset();wait.resolve(method==='workspaceGet'?{sessionId:'current',directory:'D:/workspace',revision:1,available:true,configured:true}:snapshot());await pending;assert.equal(f.view.state.task,null);assert.equal(f.view.state.workspace,null);assert.equal(f.view.state.busy,'');}});
test('审批逐字绑定原提案，授权调用携带身份与修订',async()=>{const f=fixture();await f.view.propose('t','r',proposal);await f.view.approve();assert.deepEqual(f.calls.slice(1),[['ask','execution/start','exact bytes 中文'],['answer',9,'allowed-once'],['authorize','current','execution-2',1,'a'.repeat(64),9]]);assert.equal(f.view.state.task.phase,'admitted');});
test('审批在途切换会话后不再回答票或发授权',async()=>{const wait=deferred();const f=fixture({approvalAsk:()=>wait.promise});await f.view.propose('t','r',proposal);const pending=f.view.approve();f.change('other');f.view.reset();wait.resolve({approvalId:9});await pending;assert.ok(!f.calls.some(c=>c[0]==='answer'||c[0]==='authorize'));});
test('门禁关闭不请求启动；停止带预期修订；关闭消费不停止',async()=>{const f=fixture();await f.view.propose('t','r',proposal);await f.view.start();assert.ok(!f.calls.some(c=>c[0]==='start'));assert.match(f.view.state.error,/探针/);await f.view.stop();assert.deepEqual(f.calls.at(-1),['stop','current','execution-2',1]);const n=f.calls.length;f.view.dispose();assert.equal(f.calls.length,n);});
test('恢复引用仅描述，不重提、不授权、不启动',async()=>{const f=fixture();await f.view.describe('execution-2');assert.deepEqual(f.calls,[['describe','current','execution-2']]);});
const row=(cursor,streamSequence,data,extra={})=>({version:1,sessionId:'current',executionId:'execution-2',channel:'stdout',cursor,streamSequence,data:Buffer.from(data).toString('base64'),byteCount:data.length,endOfCapture:false,eof:false,truncated:false,...extra});
const page=(records,nextCursor,hasMore=false)=>({sessionId:'current',executionId:'execution-2',records,nextCursor,hasMore});
test('跨页 UTF8 拼接；分页结束不能冒充输出 EOF',async()=>{let index=0;const bytes=Buffer.from('中');const pages=[page([row(1,1,bytes.subarray(0,2))],1,true),page([row(2,2,bytes.subarray(2))],2),page([row(3,3,Buffer.alloc(0),{endOfCapture:true,eof:false,truncated:true})],3)];const f=fixture({executionOutput:async()=>pages[index++]});await f.view.propose('t','r',proposal);await f.view.output();assert.equal(f.view.state.stdout,'');await f.view.output();assert.equal(f.view.state.stdout,'中');assert.equal(f.view.state.capture.stdout.end,false);await f.view.output();assert.deepEqual(f.view.state.capture.stdout,{end:true,eof:false,truncated:true});assert.equal(f.view.state.capture.stderr.end,false);});
test('损坏输出页整页拒绝，不半页更新游标与正文',async()=>{const f=fixture({executionOutput:async()=>page([row(1,1,Buffer.from('safe')),row(2,9,Buffer.from('bad'))],2)});await f.view.propose('t','r',proposal);await f.view.output();assert.match(f.view.state.error,/不连续/);assert.equal(f.view.state.stdout,'');assert.equal(f.view.state.cursor,-1);});
test('描述不能倒退修订或改变已审核提案',async()=>{const f=fixture({executionDescribe:async()=>({...snapshot(),proposal:proposal+' '})});await f.view.propose('t','r',proposal);await f.view.describe('execution-2');assert.match(f.view.state.error,/提案改变/);assert.equal(f.view.state.task.proposal,proposal);});
test('真实 Host 消费：工作区修订、提案、审批、门禁、取消和重载',async()=>{
 const base=resolve('apps/desktop/.tmp-test');mkdirSync(base,{recursive:true});const root=mkdtempSync(join(base,'execution-view-'));writeFileSync(join(root,'session.log'),`0\tworkspace/directory\t${root.replaceAll('\\','\\\\')}\n`);
 const {HostBridge}=createRequire(import.meta.url)('../host-bridge.cjs');const b=new HostBridge(resolve(process.env.SACODE_HOST||'apps/desktop/.tmp-test/execution-desktop-packed/bin/sacode-host.exe'),fixtureHostEnv(root,{PATH:join(process.env.SystemRoot,'System32'),TEMP:root,TMP:root}));await b.start(root);
 const api={workspaceGet:()=>b.request('workspace/get',{}),executionPropose:(sessionId,taskId,requestId,proposal)=>b.request('execution/propose',{sessionId,taskId,requestId,proposal}),executionDescribe:(sessionId,executionId)=>b.request('execution/describe',{sessionId,executionId}),executionAuthorize:(sessionId,executionId,revision,proposalDigest,approvalId)=>b.request('execution/authorize',{sessionId,executionId,revision,proposalDigest,approvalId}),executionStop:(sessionId,executionId,revision)=>b.request('execution/stop',{sessionId,executionId,revision}),executionOutput:(sessionId,executionId,cursor,limit)=>b.request('execution/output',{sessionId,executionId,cursor,limit}),executionStart:()=>{throw Error('页面不应调用关闭的启动入口');},approvalAsk:(name,args)=>b.request('approval/ask',{name,args}),approvalAnswer:(approvalId,decision)=>b.request('approval/answer',{approvalId,decision})};
 const view=createExecutionTask(api,()=> 'current',()=>{});try{await view.workspace();assert.equal(view.state.workspace.revision,1);assert.equal(view.state.workspace.sessionId,'current');await view.propose('ui-task','ui-request',JSON.stringify({cwd:root,workspaceRevision:1,executable:'cmd',argv:['/c','echo never-run'],timeoutMs:1000,outputLimit:64}));assert.equal(view.state.task.phase,'awaiting-approval');await view.approve();assert.equal(view.state.task.phase,'admitted');await view.start();assert.match(view.state.error,/探针/);await view.output();assert.equal(view.state.stdout,'');await view.stop();assert.equal(view.state.task.phase,'cancelled-before-start');const id=view.state.task.executionId;view.dispose();const reload=createExecutionTask(api,()=> 'current',()=>{});await reload.describe(id);assert.equal(reload.state.task.phase,'cancelled-before-start');assert.ok(!readFileSync(join(root,'session.log'),'utf8').includes('owned-subprocess:'));reload.dispose();}finally{view.dispose();await b.stop();}
});
