import {test} from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import vm from 'node:vm';import {fileURLToPath} from 'node:url';import {createRequire} from 'node:module';import {mkdtempSync,mkdirSync,writeFileSync,readFileSync} from 'node:fs';import {join} from 'node:path';import {execFileSync} from 'node:child_process';
const bundle=await build({entryPoints:[fileURLToPath(new URL('../renderer/pages/git-workbench-state.ts',import.meta.url))],bundle:true,write:false,format:'cjs'});const ctx={module:{exports:{}}};vm.runInNewContext(bundle.outputFiles[0].text,ctx);const {parseGitStatus,createGitWorkbench}=ctx.module.exports;
test('NUL 状态支持中文、空格、重命名和截断，不把来源路径当另一个文件',()=>{const s=parseGitStatus('## main\0 M 中文 空格.txt\0R  新名.txt\0旧名.txt\0?? draft.txt\0');assert.equal(s.branch,'main');assert.equal(s.entries.length,3);assert.equal(s.entries[1].oldPath,'旧名.txt');assert.equal(s.entries[0].y,'M');assert.equal(parseGitStatus('## main\0 M complete\0 M par',true).entries.length,1);});
test('迟到状态和差异不覆盖新选择，断开页面后不会恢复结果',async()=>{let resolveStatus,resolveDiff;const identity=()=>({sessionId:'s',directory:'root'});const reply={...identity(),failure:'',exitCode:0,truncated:false,diagnostic:''};const view=createGitWorkbench({status:()=>new Promise(r=>resolveStatus=r),diff:()=>new Promise(r=>resolveDiff=r)},identity,()=>{});const pending=view.refresh();view.reset();resolveStatus({...reply,output:'## main\0 M file\0'});await pending;assert.equal(view.state.loaded,false);const diff=view.select('a','working');view.reset();resolveDiff({...reply,path:'a',scope:'working',output:'late'});await diff;assert.equal(view.state.patch,'');const failing=createGitWorkbench({status:async()=>({...reply,sessionId:'other',output:''}),diff:async()=>reply},identity,()=>{});await failing.refresh();assert.equal(failing.state.loaded,false);assert.match(failing.state.error,/当前工作区/);});
test('preload 只开放两条固定 Git 动作，不提供 shell 参数',()=>{let exposed;const require=createRequire(import.meta.url);vm.runInNewContext(readFileSync(fileURLToPath(new URL('../preload.cjs',import.meta.url)),'utf8'),{require:n=>n==='electron'?{contextBridge:{exposeInMainWorld:(_n,v)=>exposed=v},ipcRenderer:{invoke:(channel,args)=>({channel,args})}}:require(n)});assert.equal(exposed.workspaceGitStatus('s','d').channel,'sacode:workspaceGitStatus');assert.deepEqual(Object.keys(exposed.workspaceGitDiff('s','d','file','index').args),['sessionId','directory','path','scope']);});
test('真实 Host 在 Git 不可用时明确失败，不能返回干净仓库',async()=>{const root=mkdtempSync(fileURLToPath(new URL('../.tmp-test/git-missing-',import.meta.url)));writeFileSync(join(root,'session.log'),'');const {HostBridge}=createRequire(import.meta.url)('../host-bridge.cjs');const b=new HostBridge(process.env.SACODE_HOST||fileURLToPath(new URL('../dist/host/bin/sacode-host.exe',import.meta.url)),{...Object.fromEntries(Object.entries(process.env).filter(([key])=>key.toLowerCase()!=='path')),PATH:[join(process.env.SystemRoot||'C:/Windows','System32'),...(process.env.Path||process.env.PATH||'').split(';').filter(path=>/cangjie|stdx/i.test(path))].join(';'),TEMP:root,TMP:root,SACODE_USER_SETTINGS_DIR:join(root,'settings')});await b.start(root);try{await b.request('workspace/set-directory',{directory:root});const directory=(await b.request('workspace/get')).directory;const reply=await b.request('workspace/git-status',{sessionId:'current',directory});assert.equal(reply.failure,'git-process-failed');assert.equal(reply.exitCode,-1);}finally{b.stop();}});
test('真实 Git/Host：暂存、未暂存、重命名、未跟踪、身份与路径拒绝均真实且不改日志',async()=>{
 const root=mkdtempSync(fileURLToPath(new URL('../.tmp-test/git-real-',import.meta.url)));const project=join(root,'project');mkdirSync(project);const git=(...args)=>execFileSync('git',['-C',project,...args],{encoding:'utf8'});git('init','-b','main');git('config','user.name','SaCode Test');git('config','user.email','test@example.invalid');writeFileSync(join(project,'中文 空格.txt'),'old\n');writeFileSync(join(project,'old.txt'),'rename\n');git('add','--','.');git('commit','-m','fixture');writeFileSync(join(project,'中文 空格.txt'),'index\n');git('add','--','中文 空格.txt');writeFileSync(join(project,'中文 空格.txt'),'working\n');git('mv','old.txt','new.txt');writeFileSync(join(project,'untracked.txt'),'draft');writeFileSync(join(root,'session.log'),'');
 const {HostBridge}=createRequire(import.meta.url)('../host-bridge.cjs');const b=new HostBridge(process.env.SACODE_HOST||fileURLToPath(new URL('../dist/host/bin/sacode-host.exe',import.meta.url)),{...process.env,TEMP:root,TMP:root,GIT_CEILING_DIRECTORIES:root,SACODE_USER_SETTINGS_DIR:join(root,'settings')});await b.start(root);
 try{await b.request('workspace/set-directory',{directory:project});const dir=(await b.request('workspace/get')).directory;const args={sessionId:'current',directory:dir};const before=readFileSync(join(root,'session.log'),'utf8');const status=await b.request('workspace/git-status',args);assert.equal(status.failure,'');const entries=parseGitStatus(status.output).entries;assert.equal(entries.find(e=>e.path==='中文 空格.txt').x,'M');assert.equal(entries.find(e=>e.path==='中文 空格.txt').y,'M');assert.equal(entries.find(e=>e.path==='new.txt').oldPath,'old.txt');assert.ok(entries.some(e=>e.path==='untracked.txt'));
 for(const scope of ['index','working']){const diff=await b.request('workspace/git-diff',{...args,path:'中文 空格.txt',scope});assert.equal(diff.failure,'');assert.match(diff.output,scope==='index'?/\+index/:/\+working/);}
 const indexBefore=readFileSync(join(project,'.git','index'));const quoteScope=await b.request('workspace/git-diff',{...args,path:'中文 空格.txt',scope:'"bad\n'});assert.equal(quoteScope.failure,'bad-git-path');
 writeFileSync(join(project,'中文 空格.txt'),'巨型变更\n'.repeat(30000));const large=await b.request('workspace/git-diff',{...args,path:'中文 空格.txt',scope:'working'});assert.equal(large.failure,'');assert.equal(large.truncated,true);assert.ok(Buffer.byteLength(large.output)<=262144);assert.deepEqual(readFileSync(join(project,'.git','index')),indexBefore);
 const invalid=await b.request('workspace/git-diff',{...args,path:'../outside',scope:'working'});assert.equal(invalid.failure,'bad-git-path');await assert.rejects(b.request('workspace/git-status',{...args,sessionId:'other'}),/git-session-changed/);await assert.rejects(b.request('workspace/git-status',{...args,directory:root}),/git-workspace-changed/);assert.equal(readFileSync(join(root,'session.log'),'utf8'),before);
 mkdirSync(join(project,'child'));await b.request('workspace/set-directory',{directory:join(project,'child')});const child=(await b.request('workspace/get')).directory;assert.equal((await b.request('workspace/git-status',{sessionId:'current',directory:child})).failure,'workspace-is-not-repository-root');
 const plain=join(root,'plain');mkdirSync(plain);await b.request('workspace/set-directory',{directory:plain});const plainDir=(await b.request('workspace/get')).directory;assert.equal((await b.request('workspace/git-status',{sessionId:'current',directory:plainDir})).failure,'git-command-failed');
 }finally{b.stop();}
});
