import {test} from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import vm from 'node:vm';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';import {mkdtempSync,writeFileSync,readFileSync} from 'node:fs';import {join} from 'node:path';
const code=await build({entryPoints:[fileURLToPath(new URL('../renderer/pages/terminal-output-state.ts',import.meta.url))],bundle:true,write:false,format:'cjs'});const ctx={module:{exports:{}}};vm.runInNewContext(code.outputFiles[0].text,ctx);const {createTerminalOutput}=ctx.module.exports;
const reply=(rows=[],nextCursor=0,more=false)=>({sessionId:'current',page:{rows,nextCursor,more,malformed:0}});
test('输出分页按 seq 保留同名任务，不假造执行状态',async()=>{let page=0;const v=createTerminalOutput(async()=>page++?reply([{seq:4,jobId:'bash-1',text:'第二次',truncated:true}],5):reply([{seq:2,jobId:'bash-1',text:'首次\n',truncated:false}],3,true),()=> 'current',()=>{});await v.load();await v.load();assert.equal(v.state.rows.length,2);assert.equal(v.state.rows[1].truncated,true);assert.equal(v.state.rows[0].text,'首次\n');});
test('会话切换和卸载丢弃迟到输出，失败不保留旧内容',async()=>{let resolve;const v=createTerminalOutput(()=>new Promise(r=>resolve=r),()=> 'current',()=>{});const pending=v.load();v.reset();resolve(reply([{seq:0,jobId:'a',text:'late',truncated:false}],1));await pending;assert.equal(v.state.rows.length,0);const bad=createTerminalOutput(async()=>({...reply(),sessionId:'other'}),()=> 'current',()=>{});await bad.load();assert.match(bad.state.error,/身份/);assert.equal(bad.state.loaded,false);const disposed=v.load();v.dispose();resolve(reply());await disposed;assert.equal(v.state.loaded,false);});
test('损坏和不前进分页明确失败，不展示正常空态',async()=>{for(const r of [reply([],0,true),reply([{seq:3,jobId:'a',text:'x',truncated:false}],2)]){const v=createTerminalOutput(async()=>r,()=> 'current',()=>{});await v.load();assert.ok(v.state.error);assert.equal(v.state.loaded,false);}});
test('preload 仅开放有界终端回放，不接受执行命令',()=>{let api;const require=createRequire(import.meta.url);vm.runInNewContext(readFileSync(fileURLToPath(new URL('../preload.cjs',import.meta.url)),'utf8'),{require:n=>n==='electron'?{contextBridge:{exposeInMainWorld:(_n,v)=>api=v},ipcRenderer:{invoke:(channel,args)=>({channel,args})}}:require(n)});const r=api.terminalOutput('current',0,16);assert.equal(r.channel,'sacode:terminalOutput');assert.deepEqual(Object.keys(r.args),['sessionId','cursor','limit']);});
test('真实 Host 回放夹具：分页、中文截断、损坏、越权、重启和不写日志',async()=>{
 const root=mkdtempSync(fileURLToPath(new URL('../.tmp-test/terminal-',import.meta.url)));const path=join(root,'session.log');const text='0\tuser/message\tfixture\n1\tterminal/chunk\tbash-1::取证夹具，未执行 Shell\n2\tterminal/chunk\tbad-record\n3\tterminal/chunk\tbash-1::'+('中'.repeat(4000))+'\n4\tterminal/chunk\tbash-2::末条\n';writeFileSync(path,text);
 const {HostBridge}=createRequire(import.meta.url)('../host-bridge.cjs');const host=process.env.SACODE_HOST||fileURLToPath(new URL('../dist/host/bin/sacode-host.exe',import.meta.url));const env={...process.env,TEMP:root,TMP:root,SACODE_USER_SETTINGS_DIR:join(root,'settings')};let b=new HostBridge(host,env);await b.start(root);
 try{const read=(cursor,limit)=>b.request('session/terminal-output',{sessionId:'current',cursor,limit});const first=await read(0,1);assert.equal(first.page.rows[0].text,'取证夹具，未执行 Shell');assert.equal(first.page.more,true);const next=await read(first.page.nextCursor,1);assert.equal(next.page.malformed,1);assert.equal(next.page.rows[0].truncated,true);assert.ok(Buffer.byteLength(next.page.rows[0].text)<=8192);assert.equal(next.page.rows[0].text.includes('\ufffd'),false);const last=await read(next.page.nextCursor,16);assert.equal(last.page.rows[0].text,'末条');assert.equal(last.page.more,false);
 for(const params of [{sessionId:'other',cursor:0,limit:1},{sessionId:'current',cursor:-1,limit:1},{sessionId:'current',cursor:0.5,limit:1},{sessionId:'current',cursor:0,limit:17},{sessionId:'current',cursor:'0',limit:1},{sessionId:'current',cursor:0,limit:1,command:'echo nope'}])await assert.rejects(b.request('session/terminal-output',params));
 assert.equal(readFileSync(path,'utf8'),text);b.stop();b=new HostBridge(host,env);await b.start(root);assert.equal((await read(0,1)).page.rows[0].seq,1);assert.equal(readFileSync(path,'utf8'),text);
 }finally{b.stop();}
});

test('长历史页面保留有界记录并登记省略数量',async()=>{let seq=0;const v=createTerminalOutput(async()=>{const rows=Array.from({length:16},()=>({seq:seq++,jobId:'same',text:'text',truncated:false}));return reply(rows,seq,true);},()=> 'current',()=>{});for(let i=0;i<9;i++)await v.load();assert.equal(v.state.rows.length,128);assert.equal(v.state.omitted,16);assert.equal(v.state.cursor,144);v.reset();assert.equal(v.state.omitted,0);});
